PACKAGE_NAME="cros-ec-sleep-fix"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="cros_ec_sleep_kprobe"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
MAKE[0]="make KVER=$kernelver"
CLEAN="make clean"
